---
title: Nonlinear dynamics with neural networks
subtitle: Preliminary Examination
author: Anil Radhakrishnan
date: last-modified
format:
  revealjs:
    theme: [default, assets/custom.scss]
    logo: assets/ncstate_red_letter_logo.png
    slide-number: true
    chalkboard: true
    
---
# Motivation
## Motivation: Why Neural Networks?

## Motivation: Why Nonlinear Dynamics?

## Motivation: Why Nonlinear Dynamics for Neural Networks?

## Motivation: Why Neural Networks for Nonlinear Dynamics?

# Background
## Background: Differentiable Computing

## Background: Neural Networks

## Background: Backpropagation

## Background: Loss Functions

## Background: Optimization

## Background: Meta-Learning

## Background: Physics-Informed Neural Networks

# Metalearning Activation functions
## Foundation

## Insight

## Methodology

## Results (Published and Patented)

## Conclusions

## Speculations

# Background Deux

## Background: Pontryagin's Maximum Principle

## Background: Hamilton-Jacobi-Bellman Equation

## Background: Model Predictive Control

## Background: Chaos

## Background: Chaos Control

## Background: Pendulum

## Background: Kuramoto Oscillator

## Background: Array Systems

## Background: Stochasticity and noise

# Neural Network control of chaos
## Foundation

## Insight

## Methodology

## Results (Preliminary)

## Future Work

## Speculation

# Background (For the last time I promise)
## Background: Symmetries

## Background: Dynamical Systems

## Background: Controllers for Dynamical systems

## Background: Group Equivariant Neural Networks

<!-- 
## Sample Slide Title

### Example of a subtitle

We can create unordered lists:

- first item 
    - A sub item

Or ordered lists

1. Ordered list first item
    1. Nested list item

Or **bold**, *italic*, or [URL](https://ncsu.edu) text.

## Mathematics

Inline mode: $c^2 = a^2 + b^2$

Display mode: 

$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

## Columns

We could also split content between two columns:

::: {.columns}

::: {.column width="45%"}
Left column
:::

::: {.column width="45%"}
Right column
:::

:::

<https://quarto.org/docs/presentations/revealjs/#multiple-columns>

## Code Highlighting

For continuous highlighting, use `from-to` (`6-8`).

For discontinuous highlighting, use `line1, line2, ...` (`1, 4`).

To highlight lines in a progressive manner, use `range1|range2` (`|6-8|1,4|`). 

```{.python code-line-numbers="|6-8|1,4|"}
import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

<https://quarto.org/docs/presentations/revealjs/#code-blocks>

## Enable more revealjs features

The theme is built ontop of Quarto's `revealjs` implementation. So, any [features](https://quarto.org/docs/presentations/revealjs/) of available are also usable within the theme. For example, if we wanted to incorporate the [chalkboard](https://quarto.org/docs/presentations/revealjs/presenting.html#chalkboard) feature. We would use:

```yaml
format:
  ncsu-revealjs: 
    chalkboard: true
```

## Summary {#sec-summary}

### NCSU-themed presentation slide deck

The Quarto NCSU Revealjs theme is an extension of Reveal.js and
offers all of its [features](https://quarto.org/docs/presentations/revealjs/) in the context of being brand friendly to North Carolina State University.

Install the theme without this template:

```bash
quarto install extension ParticularlyPythonicBS/ncsu-revealjs
```

Install the theme with the template being present:

```bash
quarto use template ParticularlyPythonicBS/ncsu-revealjs
```

You can learn more about using RevealJS with Quarto at: <https://quarto.org/docs/presentations/revealjs/> -->